# Generated by Django 3.1.6 on 2021-02-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210228_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('forum_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.forum_users')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
        ),
    ]
