# Generated by Django 3.1.6 on 2021-03-01 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_addcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.forum_users'),
        ),
        migrations.DeleteModel(
            name='AddComment',
        ),
    ]
