# Generated by Django 3.1.6 on 2021-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210307_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
