# Generated by Django 3.1.6 on 2021-03-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_addcomment_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcomment',
            name='pic',
        ),
    ]
