# Generated by Django 3.1.6 on 2021-03-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210308_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
