# Generated by Django 3.1.6 on 2021-03-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_addcomment_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='hker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.forum_users'),
        ),
    ]
